name: Build and Deploy Flask Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # 4. Build and push Flask image
      - name: Build and push Flask image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: aditirthore/dockerized-flask:latest

      # 5. Build and push Nginx image
      - name: Build and push Nginx image
        uses: docker/build-push-action@v7
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: aditirthore/dockerized-flask-nginx:latest

      # 6. Deploy to EC2
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

        run: |

          echo "================================"
          echo "Testing EC2 connection"
          echo "================================"

          echo "EC2 host:"
          echo "$EC2_HOST"

          echo "Testing port 22..."

          nc -vz -w 10 "$EC2_HOST" 22

          echo "Port 22 is reachable."

          echo "================================"
          echo "Preparing SSH key"
          echo "================================"

          mkdir -p ~/.ssh

          echo "$EC2_SSH_KEY" > ~/.ssh/ec2_key

          chmod 600 ~/.ssh/ec2_key

          echo "Key created."

          echo "================================"
          echo "Testing SSH"
          echo "================================"

          ssh \
            -o StrictHostKeyChecking=no \
            -o ConnectTimeout=20 \
            -o BatchMode=yes \
            -i ~/.ssh/ec2_key \
            ubuntu@"$EC2_HOST" \
            "echo 'SSH connection successful'"

          echo "================================"
          echo "Deploying application"
          echo "================================"

          ssh \
            -o StrictHostKeyChecking=no \
            -o ConnectTimeout=20 \
            -o BatchMode=yes \
            -i ~/.ssh/ec2_key \
            ubuntu@"$EC2_HOST" << 'EOF'

            cd ~/dockerized-flask

            echo "Pulling latest Docker images..."

            docker compose pull

            echo "Starting containers..."

            docker compose up -d

            echo "Removing unused images..."

            docker image prune -f

            echo "Deployment completed successfully!"

          EOF
